### ISSUE TITLE
Cannot read property 'document' of null

### ISSUE THREAD

**Issue by xavi7th** [RedHatter/svelte-devtools-standalone#1]
**Describe the bug**
When I include the script tag in the document or install via npm I get the following error

``` Cannot read property 'document' of null ```

The error points to this line in standalone.js
```
  const ref = window.open('', null, 'location=off');

  while (ref.document.head.firstChild) {
    ref.document.head.removeChild(ref.document.head.firstChild);
  }
```
**Environment**
 - Browser with version :Brave Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)
- Devtools version: "github:RedHatter/svelte-devtools-standalone"
- Svelte version: "^3.31.1"

**Additional context**
I actually stubmled upon this standalone version because the devtools for some reason refuses to detect my app in dev mode.

Thank you for a great piece.

**Comment by RedHatter** [comment]
This is caused by Brave blocking the DevTools popup window. Should work fine if you enabled popups for the page.
